MTG/essentia

src/essentia/config.h
src/essentia/roguevector.h

This change enables essentia and examples to compile on FreeBSD. Besides roguevector.h, the other sticking point is atomic.h, which compiles fine if you pass in -std=c++11 and bypass the OS specific implementations.

Add FreeBSD support

---

wscript

wscript detects Ubuntu and add 'pthread' to libs, but the test didn't include Linux Mint (which is heavily based on Ubuntu).
https://github.com/MTG/essentia/issues/122

Fix issue #122: compilation with --with-cpptests fails on Linux Mint

---

src/essentia/utils/audiocontext.cpp

Ubuntu 14.04
libswresample 1.1.100
Hi
src/essentia/utils/audiocontext.cpp has syntax error if using libswresample.

Fix syntax error on using libswresample

---

src/essentia/utils/ringbufferimpl.h

I'm pretty sure this assertion is too strict: it should be possible to read a buffer up to the last sample, no?

Corrected overly strict bounds check

---

src/wscript

taglib and libyaml brew packages for OSX have messed up pkgconfig files,
with incorrect/missing include paths.

Add a hack to fix include paths for taglib and yaml on OSX. Closes #216

---

src/essentia/scheduler/network.cpp
src/essentia/scheduler/network.h

This way one can only sort the network once, and then run just a step in
the analysis and analyze audio in real time.
It might be useful to include the algorithms I wrote that just generate input from a buffer in memory (so the buffer can change with new audio data and runStep can be called again) and an algorithm that outputs to a given place in memory, for the same reason.

Separated Network::run into runPrepare and runStep

---

src/algorithms/tonal/harmonicpeaks.cpp

was accessing to negative array index when if spectralpeaks had frequencies < f0/2
it  concern all key related algorithms (HPCP ...)!
I still don't understand how now error was thrown from this badAccess

fix wrong behaviour of harmonicpeaks 

---

src/algorithms/io/audioloader.cpp

AudioLoader is never freeing AVPackets !!
Also updated deprecated avcodec_alloc_frame() to av_frame_alloc

fix huge AudioLoader memory leak 

---

build_android.sh
src/algorithms/temporal/lpc.cpp
src/algorithms/temporal/lpc.h
wscript

This adds support for compiling on android.
An example of how to build using a lightweight version of Android (with the KISS FFT) is in the 
./build_android.sh
Update the PATH to point to where you have your Android Standalone Toolchain:-
https://developer.android.com/ndk/guides/standalone_toolchain.html
I would suggest creating a customised toolchain (as suggested in on that webpage) using the make-standalone-toolchain.sh script.

Android build

---

src/wscript

Works similarly to --ignore-algos, but with the opposite effect.
An hack has been included to automatically detect the proper version of the FFT when selected, so that user has just to say --include-algos=FFT instead of, let's say, --include-algos=FFTK

Added configuration option to build only selected algorithms

---

src/algorithms/rhythm/onsetdetectionglobal.h

I found a big memory leak for the RhythmExtractor2013 which was related with the missing deletion of referenced algorithms in OnsetDetectionGlobal. Also RhythmExtractor2013 and BeatTrackerMultiFeature do not apply correctly the network->clear() principles.

Fix memory leak in RhythmExtractor2013

---

wscript

XCode 7 projects default to using bitcode and require all libraries to also be built with bitcode support. This pull request enables bitcode support via the `-fembed-bitcode` compiler flag.
Additionally on modern systems the iOS simulator uses `x86_64` architecture, which is now added to the build flags.

Updates iOS build settings for bitcode and x86_64

---

src/wscript

It's invalid to include both --cflags and --modversion in the same call

Remove --modversion flag from pkg-config calls

---

src/algorithms/tonal/oddtoevenharmonicenergyratio.cpp

Set the maximum value for the ratio to 1000(arbitrary value)
Set the ratio to 1 when the even energy is zero and the odd is less than 0.01(arbitrary value)

Modify the oddtoevenharminicenergyratio algorithm

---

src/algorithms/spectral/gfcc.cpp
src/algorithms/spectral/gfcc.h
test/src/unittest/spectral/test_gfcc.py

Add silenceThreshold parameter default to 1e-9.
Get rid of pointer to compressor function because it is not flexible as soon as one needs to run functions with different number of parameters (amp2db vs linear) or different threshold log values (amb2db db threshold vs log)
Update unit test to the new results for `testZero`

GFCC: Add silenceThreshold parameter #543

---

src/algorithms/spectral/spectralcontrast.cpp

Use round() instead of int().
Band boundaries according to the paper:
20 Hz, 330 Hz, 704 Hz, 1256 Hz, 2303 Hz, 4729 Hz, and 11 kHz.
Band boundaries in the implementation
(frequencies corresponding to the first and the last bin of each band):
22050Hz samplerate, 2048 framesize
new -- using round()
21.53320312 -- 322.9980469
333.7646484 -- 699.8291016
710.5957031 -- 1259.692383
1270.458984 -- 2314.819336
2325.585938 -- 4748.071289
4758.837891 -- 11025
old -- using int()
10.76660156-- 312.2314453
322.9980469 -- 678.2958984
689.0625 -- 1227.392578
1238.15918 -- 2260.986328
2271.75293 -- 4683.47168
4694.238281 -- 10938.86719
44100Hz samplerate, 2048 framesize
new -- using round()
21.53320312 -- 322.9980469
344.53125  -- 689.0625
710.5957031 -- 1248.925781
1270.458984 -- 2304.052734
2325.585938 …

Improve precision for computation of subband bin intervals

---

wscript

On Ubuntu 16 `platform.dist()[0]` returns "debian" instead of "Ubuntu," and `./waf` fails to compile (with `--with-python` and `--with-cpptests`) because the `-pthread` compiler flag isn't set.
Unsure how this might affect actual Debian users or if this is really just a newer GCC issue, but this doesn't seem like it will hurt.

Compile with tests on Ubuntu 16

---

wscript

This fixes build on GCC 6.3.0 with enabled gaia2. 
Same fix from MTG/gaia#64
Eigen that is included in Essentia, is not ready for C++11, which forced by GCC 6.3.0 by default.

Fix build on GCC 6.3.0

---

wscript

Bug-fix to build on CentOS 6, where native Python support only goes up to 2.6.6 and doesn't support the set syntax.

Update wscript to work on Python 2.6.6/CentOS 6

---

packaging/build_3rdparty_static_debian.sh
packaging/build_3rdparty_static_win32.sh
packaging/build_config.sh
packaging/debian_3rdparty/build_ffmpeg_nomuxers.sh
packaging/win32_3rdparty/build_ffmpeg_nomuxers.sh

Essentia requirements had been previously upgraded to require a newer
version of libav. Since then, debian and ubuntu have both moved back
to ffmpeg too.
We switch to the same version of ffmpeg used in Ubuntu 16.04, which
we currently support for essentia

Replace libav 3rdparty static dependency with ffmpeg

---

src/essentia/streaming/algorithms/vectorinput.h

Looking to the issue #696  I've found that on the first iteration the network operates with a frame size of 4096. This size is set as [prefered frame size](https://github.com/MTG/essentia/blob/365564840e1242888f1cebfaf2dcdbd0f9783634/src/algorithms/standard/stereodemuxer.h#L39) by the `StereoDemuxer` when connecting the algorithms. However, LoudnesEBUR128 [doesn't specify](https://github.com/MTG/essentia/blob/9574c4e566ac946918ad424bb9bdb875cfa4c66e/src/algorithms/temporal/loudnessebur128.h#L95) a preferred `acquireSize` and it's reset to the default (i.e. 1) after each `compute()` generating this bottleneck. Furthermore, this bug would appear for every algorithm composite featuring `Input<std::vector<StereoSample> >` (Currently only …

Fix for algorithm composites that slow down after first compute() #696 

---

src/algorithms/standard/constantq.cpp

Cast complex<Real> type for some of the constants in ConstantQ to avoid
compilation errors on Arch Linux (#739).

Fix compilation errors in ConstantQ on Arch Linux

---

src/essentia/streaming/algorithms/vectorinput.h

Moved a variable initialization to the constructor in order to make it backwards compatible with compilers prior to c11.  
All tests in `test_vectorinput_streaming` are still passed and tests in `test_loudnessebur128` are also passed without slowdowns.

moved _acquireSize initialization to the constructors in VectorInput

---

test/src/unittests/standard/test_nsgconstantq.py

Fixes #749 by casting the result of the division to `int`.

NSGConstantQ testNyquist unit test failing in python 3

---

src/algorithms/standard/constantq.cpp
wscript

- New waf configure flag for the C++ standard (force C++11 by default)
- Fix compìlation error in ConstantQ

Add flag for C++ standard (force C++11 by default)

---

src/algorithms/tonal/chordsdescriptors.cpp
src/algorithms/tonal/chordsdescriptors.h
src/essentia/essentiamath.h
src/python/essentia/utils.py
src/python/globalfuncs.cpp
test/src/unittests/tonal/test_chordsdescriptors.py

This PR complements the recently added key updates (#814):
- updates  [ChordsDescriptors](https://github.com/MTG/essentia/blob/96531284a35ef6142c6e6ed80cad8b82a9751e2e/src/algorithms/tonal/chordsdescriptors.cpp) to accept the new [chord names](https://github.com/MTG/essentia/blob/08f04f61fc5439396871ec2498f28a03eb3b090e/src/algorithms/tonal/key.cpp#L80) used by `Key`.
- adds a function `equivalentKey` that given a chord name provides an equivalent name when available (e.g,  `equivalentKey(C#)` returns `Db`).
- a python wrapper for `equivalentKey`.

Key updates fixes

---

src/algorithms/tonal/chordsdescriptors.cpp
test/src/unittests/tonal/test_chordsdescriptors.py

In the previous note naming convention sharp ("#") was used to name every not natural note and it was safe to capitalize the whole key string as "#" is not affected by `toUpper`.
Now the `Key` algorithm also outputs some flats ("b") so `toUpper` cannot be applied to the accidental anymore as "B" is not accepted for flat.

Prevent the accidental (b or #) from being capitalized in ChordsDescriptors

---

src/algorithms/standard/nsgconstantq.cpp
src/algorithms/standard/nsgconstantq.h
src/algorithms/standard/nsgconstantqstreaming.h
src/algorithms/standard/nsgiconstantq.cpp
src/algorithms/standard/nsgiconstantq.h
test/src/unittests/standard/test_nsgconstantq.py
test/src/unittests/standard/test_nsgiconstantq.py

This PR contains a few small changes to improve the algorithm's performance with the default parameters.
- updated default parameters so they work better in most of the cases.
- repeat the last sample if the input signal is odd so FFT does not throw an exception.
- add a unit test to assert it don't throw exceptions on odd signals as before.

NSGConstantQ: Update the default parameters and repeat the last sample in odd signals

---

src/algorithms/temporal/loudnessebur128.cpp
src/algorithms/temporal/loudnessebur128.h
test/src/unittests/temporal/test_loudnessebur128.py

This may be useful when one wants to syncronize positons of the values of
instantaneous and short-term loudness. Otherwise the value do not correspond
to the same time positions because of the difference in the size of sliding windows.

Add option to zero-center windows for EBU R128 loudness estimation

---

src/algorithms/spectral/gfcc.h
src/algorithms/spectral/mfcc.cpp
src/algorithms/spectral/mfcc.h
src/essentia/essentiamath.h
src/python/globalfuncs.cpp
test/src/unittest/spectral/test_hpcp.py

- Add silenceThreshold parameter to MFCC and GFCC
- Add configurable thresholding to lib2db, pow2db, amp2db
- Change silence threshold to 1e-10
This is a big change for MFCC/GFCC values, therefore, this PR should be tested in terms of the resulting performance of classifier models based on MFCCs/GFCCs (does the accuracy improve?).

Update MFCC thresholding

---

.gitignore
src/algorithms/rhythm/beattrackerdegara.cpp

Make Degara beattracker deterministic by not adding stochastic noise to silent frames

Make Degara beattracker deterministic

---

src/algorithms/standard/peakdetection.cpp
src/algorithms/standard/peakdetection.h
test/src/unittests/standard/test_peakdetection.py

This PR adds a new parameter `minPeakDistance` that sets the minimum distance between contiguous peaks. A value of `0` (by default) will bypass this feature. The algorithm uses an amplitude criterium to choose which peaks to delete.

Minimum peak distance parameter for PeakDetection

---

src/algorithms/highlevel/pca.cpp
src/examples/standard_pca.cpp
src/examples/wscript

Creation of a new `Array2D` `outFeatVector` with the desired output shape so that `featVector` does not have to be resized. This PR solves the bug described in #727. It also includes a .cpp file that can be included as use example.

PCA invalid memory access fix

---

src/3rdparty/cephes/bessel/bessel.h
src/3rdparty/cephes/bessel/gamma.cpp
src/3rdparty/cephes/bessel/hyperg.cpp
src/3rdparty/cephes/bessel/iv.cpp
src/3rdparty/cephes/bessel/polevl.cpp

Closes #878 
As the 3rd party library is only compiled when the algorithms that need it are required it would be not direct to create python bindings and units tests that depend on the `INCLUDE_ALGOS` list. For now, I will just left here some values for the `iv` Bessel function obtained with Scipy and Essentia so they can be checked again if any further modification of this dependancy is produced.
**Scipy values**
iv(0, 0):     1.0
iv(0, -0.9):  1.21298516573
iv(0, 0.9):   1.21298516573
iv(1, 0):     0.0
iv(1, -0.9): -0.497126448161
iv(1, 0.9):   0.497126448161
**Essentia values**
[   INFO   ] iv(0, 0.0): 1
[   INFO   ] iv(0, -0.9): 1.21299
[   INFO   ] iv(0, 0.9): 1.21299
[   INFO   ] iv(1, 0.0): 0
[   INFO   ] iv(1, -0.9): -0.497126
[   INFO   ] iv(1, 0.9): 0.497126

Cephes iv Bessel function fix

---

src/essentia/roguevector.h
wscript

Fix cross-compilation for Android (#622). Use clang and libc++ as
they are the ones that will be supported in the future (gcc is
depricated).

Fix cross-compilation for Android

---

src/python/essentia/common.py
src/python/pytypes/vectorvectorreal.cpp

Add support for conversion of Python lists of 1d numpy arrays to
VECTOR_VECTOR_REAL in the type wrapper. Previously, only
conversion from a list of lists of Python floats was supported
(see 4d8e9696a5084728c787e9b42c8bcf96fb907bfe).

Faster VECTOR_VECTOR_REAL conversion from python types

---

src/essentia/essentiamath.h
src/python/essentia/utils.py
src/python/globalfuncs.cpp
test/src/unittests/spectral/test_gfcc.py
test/src/unittests/spectral/test_mfcc.py

Added a new `testZero` unit test for each available `logType` as suggested in #731.  Also added a line to test that nans or infs are never returned.  For now, `testZeroLog`  will fail until we merge [mfcc_thresholding](https://github.com/MTG/essentia/tree/mfcc_thresholding).

MFCC/GFCC: added a testZero for every `logType`

---

src/algorithms/audioproblems/clickdetector.cpp
src/algorithms/spectral/triangularbands.cpp
src/algorithms/standard/peakdetection.cpp
src/algorithms/stats/histogram.cpp
src/algorithms/tonal/pitchyinprobabilistic.cpp
src/algorithms/tonal/pitchyinprobabilities.cpp
src/algorithms/tonal/pitchyinprobabilitieshmm.cpp
src/essentia/configurable.cpp
src/essentia/utils/metadatautils.h

This PR removes all the compilation warnings not related to `AVStream` in my Ubuntu 18.04.2 LTS machine

Compilation warnings fixes

---

src/python/essentia/pytools/spectral.py

Added a one-liner python function in essentia.pytools to compute [essentia.standard HPCP](http://essentia.upf.edu/documentation/reference/std_HPCP.html) features from an input audio vector.
```python
from essentia.standard import MonoLoader
import essentia.pytools.spectral as sp
audio_vector = MonoLoader("<path_to_your_audio_file>")
hpcp = sp.hpcpgram(audio_vector, frameSize=4096, hopSize=2048) # with default params
```

Added one-liner function for HPCP in essentia.pytools

---

doc/sphinxdoc/streaming_extractor_music.rst
src/algorithms/extractor/musicextractor.cpp
src/algorithms/extractor/musicextractor.h
src/examples/standard_chromaprinter.cpp
src/examples/wscript

This pull request modifies [MusicExtractor](http://essentia.upf.edu/documentation/reference/std_MusicExtractor.html) to compute a Chromaprint  when libchromaprint is installed as demanded on  #718.
In such case two new parameters are added to MusicExtractor:
- **chromaprintCompute** : a flag to compute the Chromaprint. Defaults to `false`.
- **chromaprintDuration** : the amount of time from the beginning used to compute the Chromaprint. 0 to use the full audio length. Defaults to the full audio length.
The parameters can also be configured through the Yaml file with the following lines as explained [here](http://essentia.upf.edu/documentation/streaming_extractor_music.html#configuration):
```
chromaprint:
<tab>duration: 10.0
<tab>compute: true
```

MusicExtractor: compute a chromaprint when libchromaprint is available

---

Essentia Licensing.txt
FAQ.md
doc/sphinxdoc/installing.rst
doc/sphinxdoc/licensing_information.rst
packaging/build_3rdparty_static_debian.sh
packaging/build_config.sh
packaging/debian_3rdparty/build_eigen3.sh
src/algorithms/io/yamloutput.cpp
src/essentia/essentiautil.h
src/essentia/pool.cpp
src/essentia/pool.h
src/essentia/types.h
src/python/essentia.cpp
src/python/essentia/common.py
src/python/parsing.cpp
src/python/pyalgorithm.cpp
src/python/pytypes/pypool.cpp
src/python/pytypes/tensorreal.cpp
src/python/pytypes/vectortensorreal.cpp
src/python/typedefs.h
src/wscript
test/src/unittests/base/test_pool.py
test/src/unittests/essentia_test.py
test/src/unittests/io/test_yamloutput.py

We decided to make Eigen3 an external dependency attending to these reasons:
- reduce the amount of fixed src in Essentia
- allow better compatibility with Gaia
- make it easy to update
Also, this is a first step towards substituting TNT by Eigen so it was decided to make it already a required dependancy even if we only use it for tensors (4D matrices) right now.
This PR also adds the following features:
- New types `Tensor<>` and `TensorMap<>`
- Support for `Tensor<Real>` and `VectorTensor<Real>` in Pools
- `set()` and `add()` methods for those
- Python interface for Pools with tensors
- packaging scripts for Eigen3
- update Gaia to a version that relies on Eigen as an external package
- updated documentation and Licensing info

Support Eigen3 as a required external dependency

---

travis/build_wheels.sh

We are dropping support for Python 3.4 since PyYaml is not supporting it anymore.
We can just remove the Python3.4 folder until ManyLinux1 drops the support too. 
This way, we prevent making skip conditions in two 2 different loops so the code doesn't get too messy.

Drop support for Python 3.4 wheels

---

src/algorithms/standard/vectorrealtotensor.cpp
src/algorithms/standard/vectorrealtotensor.h
test/src/unittests/machinelearning/test_tensorflowpredict.py
test/src/unittests/machinelearning/test_tensorflowpredict_streaming.py
test/src/unittests/streaming/test_tensortopool.py
test/src/unittests/streaming/test_vectorrealtotensor.py

- Improve the logic to decide if a patch should be added when shouldStop()
- Do not add a last patch in repeat mode when there are 0 frames remaining
- Remove unnecessary `_pushedEverything` variable
- Improve comments and exception information
Additionally, several unit tests are added.

VectorRealToTensor fixes

---

test/src/unittests/machinelearning/test_tensorflowpredictvggish.py

- Recompute expected values with a smaller VGGish. In this model the number of filters and dense units is divided by 64. The weights are random. Just to check for unexpected regression values.
- Point to a newer [essentia-models](https://github.com/MTG/essentia-models/commit/c726312eaa4f637a65775145fe5329ee160c5959) commit

Update VGGish test

---

src/algorithms/highlevel/chromacrosssimilarity.cpp
src/algorithms/highlevel/chromacrosssimilarity.h
src/algorithms/highlevel/coversongsimilarity.cpp
src/algorithms/highlevel/coversongsimilarity.h
src/algorithms/highlevel/crosssimilaritymatrix.cpp
src/algorithms/highlevel/crosssimilaritymatrix.h
src/examples/standard_chromacrosssimilarity.cpp
src/examples/standard_coversongsimilarity.cpp
src/examples/standard_crosssimilaritymatrix.cpp
src/examples/streaming_chromacrosssimilarity.cpp
src/examples/streaming_coversongsimilarity.cpp
test/src/unittests/highlevel/test_chromacrosssimilarity.py
test/src/unittests/highlevel/test_coversongsimilarity.py

This PR address the following changes.
-  Fix typos and formatting in the music similarity category algorithms to improve the documentation.
- Fixed a bug in the streaming mode [`CoverSongSimilarity`](https://essentia.upf.edu/reference/streaming_CoverSongSimilarity.html) algorithm while computing the sub-sequence alignment and updated the examples and unit tests.
- Updated copyright year range in these files.

Fix docstrings and added some improvements in streaming mode music similarity 

---

src/3rdparty/tensorflow/setup_from_python.sh
src/3rdparty/tensorflow/setup_tensorflow.py

Add a functionality to `setup_tensorflow.py` to work out `libtensorflow_framework`'s version.
With this change we can now link against TensorFlow 2.X Python wheels too.
Fixes #1001

libtensorflow_framework.so.2 support 

---

wscript

A couple of fixes for the `run_python_test` Waf method:
- Replace 'is not' by '!=' for literals, which throws a warning in Python 3.8.
- Don't overwrite PYTHONPATH when running the unit tests, so the user's required packages located in PYTHONPATH directories are correctly loaded.
This solves one of the issues described in  #914

Waf run_python_tests fixes

---

src/algorithms/standard/tensornormalize.cpp
src/algorithms/standard/tensornormalize.h
src/algorithms/standard/tensortranspose.cpp
src/algorithms/standard/tensortranspose.h
src/algorithms/standard/vectorrealtotensor.cpp
src/essentia/essentiamath.h
src/essentia/types.h
src/python/parsing.cpp
src/python/pytypes/pypool.cpp
src/python/pytypes/tensorreal.cpp
src/wscript
test/src/unittests/standard/test_tensornormalize.py
test/src/unittests/standard/test_tensortranspose.py

This PR contains several improvements related to  Eigen Tensors:
- TensorReal toPythonRef -> toPythonCopy to fix #1013 
- Add convenience aliases for tensors of different ranks
- Disable build-time Eigen-related warnings
- Add basic statistic operations with tensors (mean, std, min, max)
- Add new Algorithms `TensorTranspose` & `TensorNormalize`

Several improvements related to  Eigen Tensors

---

doc/sphinxdoc/installing.rst

Bash on Ubuntu is now the Windows Subsystem for Linux
I kept the notes a little bit less specific, since I think the Linux notes should suffice

Update Installing notes for WSL

---

src/algorithms/io/monoloader.h
src/essentia/streaming/algorithms/devnull.cpp

Memory leaks were previously found in the MonoLoader standard class due to the `NOWHERE` connections. Here's a simple program to reproduce it:
```cpp
// TestMonoLoader.cpp
#include <memory>
#include <string>
#include <vector>
#include <essentia/algorithm.h>
#include <essentia/algorithmfactory.h>
#include <essentia/essentia.h>
int main()
{
std::string testFileName = "<audioFileName>";
essentia::init();
std::unique_ptr<essentia::standard::Algorithm> monoloader(essentia::standard::AlgorithmFactory::create("MonoLoader", "filename", testFileName, "sampleRate", 16000));
std::vector<essentia::Real> monoOut;
monoloader->output("audio").set(monoOut);
monoloader->compute();
essentia::shutdown();
return 0;
}
```
The output on running this with valgrind without the fix is:
```sh
$ valgrind …
```

Fixed mem leak in MonoLoader - Disconnect DevNulls

---

src/algorithms/stats/histogram.cpp

The previous histogram logic had a bug which lead to undefined behavior. For example, suppose the min, max values and the bin width of the histogram are set to be 10, 25 and 1 respectively. The number of bins for this histogram would then be 15. If the input array for which the histogram is to be computed has a value of `21` in it, the bin value to be incremented by the old logic would be:
`floor(array[i]/(Real)binWidth` = floor(21/1.0f) = `21`
In line 60 of histogram.cpp, the vector histogram would be resized to `_numberBins` which in this case is `15`. Accessing `histogram[21]` would be illegal but C++ doesn't not define the behavior for such an OutOfBounds access operation (refer `Notes` section [here](https://en.cppreference.com/w/cpp/container/vector/operator_at)).
This PR fixes the …

Fixed OutOfBounds access to vector in Histogram

---

src/algorithms/rhythm/loopbpmconfidence.cpp
test/src/unittests/rhythm/test_loopbpmconfidence.py
test/src/unittests/rhythm/test_loopbpmestimator.py

During Unit Tests a minor issue was found was found in loopbpmconfidence.cpp, when dealing with empty incoming signals. A fix was added for this.
The "techno_loop.wav'" recording forms the basis of the tests, using the whole signal and parts of the signal for different checks.

Unit tests for LoopBpmEstimator and LoopBpmConfidence

---

src/algorithms/tonal/pitchcontoursmultimelody.cpp

Fixes #1054; #835 may be related too. There is a loop that keeps adding new elements to `pitches` instead of updating the existing ones, therefore the loop never ends and the vector eventually fills up the memory.

Fix infinite loop in PitchContoursMultiMelody

---

src/algorithms/tonal/pitchcontours.cpp
test/src/unittests/tonal/test_pitchmelodia.py

Fixing a bug that occurs when there is a non-zero number of frames, but none of them have any peaks (e.g. when the audio signal is all zeros). In this situation, [this check](https://github.com/cifkao/essentia/blob/ba79be6515f2fd0cde75ee3f6fa98706a66f4c36/src/algorithms/tonal/pitchcontours.cpp#L71) is not triggered and an error occurs [here](https://github.com/cifkao/essentia/blob/ba79be6515f2fd0cde75ee3f6fa98706a66f4c36/src/algorithms/tonal/pitchcontours.cpp#L137) (trying to compute the mean of an empty array). The fix is to find the salient bin indices first, and then check if the result is non-empty.
Also adding a test for this.

Fix PitchContours when no salient frames present

---

src/algorithms/tonal/tonicindianartmusic.cpp
test/src/unittests/tonal/test_key.py
test/src/unittests/tonal/test_tonicindianartmusic.py

While testing tonicindianartmusic.cpp, I found a some cases where segmentation faults occur. Initially I thought that it was related to the empty audio, but on closer examination, in a test case where you send in a pure sine wave with a frequency below the configured minTonicFrequency, can produce a set of empty peaks and consequently a segmentation fault.
I added 8 test cases. They may not cover all config combinations, but catch the typical illegal ones (e.g.  min and max Tonics conflicting), but its a start to at least give good coverage to the change in the CPP file.

Indian tonic: Fixed bug relating to use cases that produced empty peaks

---

FAQ.md
packaging/build_config.sh
packaging/debian_3rdparty/build_tensorflow.sh
setup.py
src/3rdparty/tensorflow/setup_from_libtensorflow.sh
travis/build_wheels.sh

Update the `build_tensorflow.sh` and TensorFlow dependency version.
Now TensorFlow is built with Bazel on its monolithic configuration. This is a shared library with an almost static behavior.
Critically, the monolithic version of `libtensorflow.so` does not depend on `framework_tensorflow.so` which contains the capability to register ops from outside the library and was the cause of the clash with the TensorFlow wheel.
Also, the `essentia-tensorflow` wheels are linked against our TensorFlow build, so TensorFlow is not a Python setup dependency anymore.
This approach gives us the capability to make `essentia-tensorflow` wheels up to the latest Python version (3.9 at the moment).

Monolithic build of Tensorflow 2.5

---

src/algorithms/machinelearning/tensorflowpredict.cpp
src/algorithms/machinelearning/tensorflowpredict.h
src/algorithms/machinelearning/tensorflowpredictmusicnn.cpp
src/algorithms/machinelearning/tensorflowpredictmusicnn.h
src/algorithms/machinelearning/tensorflowpredicttempocnn.cpp
src/algorithms/machinelearning/tensorflowpredicttempocnn.h
src/algorithms/machinelearning/tensorflowpredictvggish.cpp
src/algorithms/machinelearning/tensorflowpredictvggish.h
src/algorithms/rhythm/tempocnn.cpp
src/algorithms/rhythm/tempocnn.h
test/src/unittests/essentia_test.py
test/src/unittests/machinelearning/test_tensorflowpredict.py
test/src/unittests/machinelearning/test_tensorflowpredictmusicnn.py
test/src/unittests/machinelearning/test_tensorflowpredicttempocnn.py
test/src/unittests/machinelearning/test_tensorflowpredictvggish.py
test/src/unittests/rhythm/test_tempocnn.py

This PR gives `TensorflowPredict` and derivate algorithms the capability to run Tensorflow SavedModels.
When both `savedModel` and `graphFilename` are specified, the first one is preferred
Additionally, it modifies `TensorflowPredict`'s behavior so that the configuration is skipped  when `graphFilename` or/and `savedModel` are set to an empty string ("").
The main benefit is that algorithms depending on `TensorflowPredict` can default `graphFilename` and `savedModel` to an empty string and leverage the skip-configuration logic implemented on `TensorflowPredict`.
This also simplifies the logic required to choose between the `graphFilename` and `savedModel` when both are specified.

Support Tensorflow models in SavedModel format

---

src/algorithms/machinelearning/tensorflowpredict.h

Small PR to remove unused `metaGraphDef` variable from `TensorflowPredict`

Remove metaGraphDef variable

---

src/algorithms/machinelearning/tensorflowpredictcrepe.cpp
src/algorithms/machinelearning/tensorflowpredictmusicnn.cpp
src/algorithms/machinelearning/tensorflowpredicttempocnn.cpp
src/algorithms/machinelearning/tensorflowpredictvggish.cpp

Now `graphFilename` defaults to an empty string, so it's always configured
and this check doesn't make sense.

Remove outdated check

---

src/algorithms/machinelearning/tensorflowpredict.cpp

There should be at least 2 dimensions (batch, data)
This fixes a segmentation fault that happens when you feed a scalar input (i.e., `shape(1,1,1,1)`).
However, I didn't prepare a test because we don't have models that work with scalars. 
I could create a TensorFlow model consisting of a single identity layer expecting a scalar, but this is probably a corner case without practical applications for which we don't want to store an additional model.

Fix squeeze bug

---

src/algorithms/machinelearning/tensorflowpredictcrepe.cpp
src/algorithms/machinelearning/tensorflowpredictcrepe.h
src/algorithms/tonal/pitchcrepe.cpp
src/algorithms/tonal/pitchcrepe.h
test/src/unittests/machinelearning/test_tensorflowpredictcrepe.py

This change makes this algorithm consistent with other algorithms from the TensorflowPredict* family
(Remake of #1216)

Support SavedModels in Crepe

---

src/algorithms/machinelearning/tensorflowpredict.cpp
test/src/unittests/machinelearning/test_tensorflowpredict.py

Throw an exception if a `savedModel` is not loaded successfully.
This solution mimics the way we handle unsuccessful load of protocol buffers (`graphFilename`)

Handle unsuccessful load of savedModel

---

src/algorithms/machinelearning/tensorflowpredictmusicnn.cpp
src/algorithms/machinelearning/tensorflowpredictmusicnn.h
src/algorithms/machinelearning/tensorflowpredictvggish.cpp
src/algorithms/machinelearning/tensorflowpredictvggish.h
test/src/unittests/machinelearning/test_tensorflowpredictvggish.py

Adds a  `patchSize` parameter so that `TensorflowPredictMusiCNN` and TensorflowPredictVGGish` can be use with derivate models expecting different input patch sizes.
Right now, we test this functionality  by assessing that an incorrect batch size produces an exception in VGGish. This approach can't be followed with MusiCNN as it accepts a dynamic input patch size.

Add patchSize parameter

---

src/algorithms/machinelearning/tensorflowpredictcrepe.h
src/algorithms/machinelearning/tensorflowpredicteffnetdiscogs.cpp
src/algorithms/machinelearning/tensorflowpredicteffnetdiscogs.h
src/algorithms/machinelearning/tensorflowpredictmusicnn.cpp
src/algorithms/machinelearning/tensorflowpredictmusicnn.h
src/algorithms/machinelearning/tensorflowpredicttempocnn.cpp
src/algorithms/machinelearning/tensorflowpredicttempocnn.h
src/algorithms/machinelearning/tensorflowpredictvggish.cpp
src/algorithms/machinelearning/tensorflowpredictvggish.h
src/algorithms/rhythm/tempocnn.h
src/algorithms/standard/vectorrealtotensor.cpp
src/algorithms/standard/vectorrealtotensor.h
src/algorithms/tonal/pitchcrepe.h
test/src/unittests/machinelearning/test_tensorflowpredicteffnetdiscogs.py
test/src/unittests/streaming/test_vectorrealtotensor.py

A series of improvements related to the management of the batch size:
1. Support both `0` and `-1` to activate the accumulate mode (see VectorRealToTensor's [documentation](https://essentia.upf.edu/reference/streaming_VectorRealToTensor.html)) as discused in https://github.com/MTG/essentia/pull/1236#issuecomment-1049841378.
2. Add a parameter `lastBatchMode` in `VectorRealToTensor`. Before, if `batchSize` was larger than 1, the last patches not fitting an entire final batch were discarded. The new option `push` (default) creates a final batch with the remaining patches. Note that this option is not suitable for models expecting a fixed batch size (e.g., EffnetDiscogs).
3. Implement the `batchSize` parameter in `TensorflowPredictMusiCNN` and `TensorflowPredictVGGish` for consistency with …

Batch size management improvements

---

src/examples/wscript

This change makes sure the user can define the location of the vamp 3rd-party plugin at configure-time

Prefix for vamp linux install path

---

src/algorithms/standard/windowing.cpp
src/algorithms/standard/windowing.h
src/essentia/essentiamath.h
test/src/unittests/standard/test_windowing.py

Implement a parameter `constantsDecimals` to allow choosing the number of decimals used in the constants for the formulation of the Hamming and Blackman-harris windows as demanded in #1199.
This functionality provides more flexibility in order to replicate alternative window implementations. In this case, we test that we can replicate the Hamming windows produced by SciPy.

constantsDecimals parameter for Windowing

---

doc/sphinxdoc/_templates/sphinxdoc_mtg/static/base.css

Set explicit limits for the bodywrapper div from 0 to 1270. This means that the the body text will occupy all the space available up to 1270 pixelsi horizontally.
Additionaly, set the width of main-containter to 100% to prevent overflow when the section is inside bodywraper. This only affect to pages with sideber.

Improve resizing for pages with a sidebar

---

src/algorithms/standard/unaryoperator.cpp
test/src/unittests/standard/test_unaryoperator.py

Unaryoperator bugfix

---

src/algorithms/tonal/pitchyinfft.cpp

Small fix in PitchYINFFT.
Sorry, I reverted the first commit because I had an issue in my fork.

Framebuffer - Issue in PitchYINFFT when no peaks are detected.

---

.github/workflows/build-docs.yml
doc/sphinxdoc/_templates/search.html
doc/sphinxdoc/_templates/sphinxdoc_mtg/base.html
doc/sphinxdoc/conf.py
doc/sphinxdoc/installing.rst

These changes should restore Sphinx search functionality to the Essentia documentation website.
Roughly speaking: the custom `search.html` template in `essentia.git` has drifted from the JavaScript files and interfaces provided during a Sphinx HTML documentation build.
Additionally, the `sphinxprettysearchresults` extension is removed; it was a workaround for a bug that caused unclearly-formatted search results that was fixed in v2.0.0 of Sphinx.
No server-side changes are required with this change.
Resolves #1198.

Maintenance: restore Sphinx documentation seach functionality

---

src/algorithms/tonal/pitchyinfft.cpp
src/algorithms/tonal/pitchyinfft.h

1) Add weighting parameter to select different weighting funcitons in PITCHYINFFT algorithm. The available choices are: 
- the default weighting function
- A-weighting
- B-weighting
- C-weighting
- D-weighting
- Z-weighting.
Note that there is not experimental validation of better pitch estimation performance with new alternative weightings. 
2) Change behavior on empty spectrum peak detection: output zero pitch and confidence instead of throwing an exception.
@dbogdanov Edited for completeness.

PitchYinFFT updates (new weighting parameter, do not throw exception on empty peak detection)

---

.github/workflows/build-wheels-cibuildwheel.yml
pyproject-tensorflow.toml
pyproject.toml
setup.py
wscript

In theory, Apple Silicon wheels can be cross-compiled from the intel mac machines (however the can't be tested):
https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon
Additionally, we replace `os.system` calls by `subprocess.run` so that we can notice when one of these subprocesses fail.

Add changes to support building arm64 macos wheels

---

doc/Doxyfile
doc/sphinxdoc/generate_reference.py
doc/sphinxdoc/installing.rst

Display jupyter notebook tutorials using the algorithm in its documentation page

[feat] Add related tutorials in algorithms docs

---

doc/sphinxdoc/generate_reference.py
doc/sphinxdoc/installing.rst

Add links to C++ source and header file for each algorithm

[feat] Support source code links from algorithm reference

---

doc/sphinxdoc/generate_reference.py

Following fixes have been applied -
- Algorithm definition files are obtained via matching name fields in `cpp` files instead of matching file names
- `Related tutorials` section updated to bring it closer stylistically to `See also` section
Old
New

[fix] Improvements in doc generation

---

src/algorithms/tonal/pitchyinprobabilities.cpp
src/essentia/essentiamath.h
src/python/essentia/utils.py
src/python/globalfuncs.cpp
test/src/unittests/base/test_utils.py

Add some hertz, midi note number and note conversions:
- hz2midi
- midi2hz
- hz2cents
- cents2hz
- midi2note
- note2midi
- note2hz
- hz2note
- db2velocity
- velocity2db

Add essentiamath

---

doc/build_sphinx_doc.sh
doc/sphinxdoc/conf.py
doc/sphinxdoc/generate_reference.py

Following changes have been made:
- Generate rst version of `algorithms_reference` file for automatic indexing in sidebar
- Disable explicit generation of algorithms` html versions. Use rst files to automatically generate htmls.

[feat] Add sidebar in algorithms reference page

---

src/essentia/essentiamath.h

Floor function was not working properly with an integer. 
After converting to float values, the octave value has been fixed.

Fix issue with the octaves left from the reference

---

.github/workflows/build-docs.yml
.github/workflows/build-wheels.yml

Update `upload-artifact` checkout version from `v2` to `v4` in following workflow files -
- `build-docs`
- `build-wheels`

[fix] Update deprecated artifact action versions

---

src/algorithms/highlevel/chromaprinter.cpp
src/essentia/essentiamath.h
src/essentia/types.h
src/essentia/utils/peak.h

This PR fixes build errors encountered when compiling Essentia with C++17 due to the removal of functions deprecated in C++11 (std::bind1st, std::binary_function). These deprecated functions have been replaced by the recommended alternatives (std::bind with placeholders and direct implementation without inheriting from std::binary_function).
Ensures compatibility and successful compilation with modern C++ standards (C++17 and newer), improving maintainability and future-proofing the codebase.
- **Issue #1206**: Compilation failure due to the removal of `std::binary_function` in C++17.
- **Pull Request #1370**: Initial fixes for C++17 compatibility issues.
Inspired by the work of [@wo80](https://github.com/wo80) in commit [c98daf9](https://github.com/wo80/essentia/commit/c98daf92f9506dab092 …

Fix build issues with deprecated functions in C++17

---

pyproject-tensorflow.toml
pyproject.toml
src/python/globalfuncs.cpp
src/python/pytypes/matrixreal.cpp
src/python/pytypes/tensorreal.cpp
src/python/pytypes/vectorcomplex.cpp
src/python/pytypes/vectorinteger.cpp
src/python/pytypes/vectormatrixreal.cpp
src/python/pytypes/vectorreal.cpp
src/python/pytypes/vectorstereosample.cpp
src/python/pytypes/vectortensorreal.cpp
src/python/pytypes/vectorvectorcomplex.cpp
src/python/pytypes/vectorvectorreal.cpp
src/python/pytypes/vectorvectorstereosample.cpp
test/src/unittests/synthesis/test_harmonicmodel_streaming.py
test/src/unittests/synthesis/test_hprmodel_streaming.py
test/src/unittests/synthesis/test_hpsmodel_streaming.py
test/src/unittests/synthesis/test_sinemodel_streaming.py
test/src/unittests/synthesis/test_sprmodel_streaming.py
test/src/unittests/synthesis/test_spsmodel_streaming.py
test/src/unittests/tonal/test_pitchsaliencefunctionpeaks.py
test/src/unittests/tonal/test_tonicindianartmusic.py

- Updates Python bindings to NumPy v2 C-API.
- Drops support for Python wheels < 3.9.
- Fixes in unit tests. Remove deprecated NumPy submodule.
Very similar changes were proposed in PR #1470 in 7636b9949330d496d6a999cd91fa4b481c24c2b1.

Update to NumPy 2 C-API
