- src/algorithms/SuperFlux/SuperFlux/SuperFluxExtractor.cpp
- src/algorithms/SuperFlux/SuperFlux/SuperFluxExtractor.h
- src/algorithms/SuperFlux/SuperFlux/SuperFluxNovelty.cpp
- src/algorithms/SuperFlux/SuperFlux/SuperFluxPeaks.cpp
- src/algorithms/SuperFlux/SuperFlux/SuperFluxPeaks.h
- src/algorithms/SuperFlux/filter/MaxFilter.cpp
- src/algorithms/SuperFlux/filter/TriangularBands.cpp
- src/algorithms/SuperFlux/filter/TriangularBands.h
bug fix for small samples
fix names typo
clean a bit
> SuperFixes

- src/algorithms/SuperFlux/SuperFlux/SuperFluxExtractor.cpp
- src/algorithms/SuperFlux/SuperFlux/SuperFluxExtractor.h
- src/algorithms/SuperFlux/SuperFlux/SuperFluxNovelty.cpp
- src/algorithms/SuperFlux/SuperFlux/SuperFluxNovelty.h
- src/algorithms/SuperFlux/SuperFlux/SuperFluxPeaks.cpp
- src/algorithms/SuperFlux/SuperFlux/SuperFluxPeaks.h
- src/algorithms/SuperFlux/filter/MaxFilter.cpp
- src/algorithms/SuperFlux/filter/MaxFilter.h
> Master superflux fix

- src/algorithms/tonal/pitchfilter.cpp
- src/algorithms/tonal/pitchfilter.h
Here are the changes related to parametrizations. 
Also I realised that we were not initialising the confidence values correctly and fixed it. (2eb63db)
> Pitchfiltermakam

- src/wscript
TODO : bug if
waf configure --lightweight=
comes from FFT selection in wscript
> build essentia_reg.cpp at configure time

- src/essentia/roguevector.h
- src/essentia/utils/atomic.h
- wscript
I should probably add instructions on how to build with Emscripten. How can I do that?
> Can now build with Emscripten targeting Javascript

- FAQ.md
- wscript
I added instructions for using Emscripten in the FAQ (long due!), and slightly modified the wscript to add emscripten options and use --emscripten instead of checking environment.
> Updated documentation and build script for Emscripten

- wscript
Support for cross compiling on iOS from OS X in lightweight mode. Configure like this:
./waf configure --cross-compile-ios --lightweight= --fft=ACCELERATE --build-static
Tested on an iPad-Air. There's also a flag to build for the simulator (so you can test on the Desktop)
> iOS support

- src/algorithms/spectral/erbbands.cpp
- src/algorithms/spectral/gfcc.cpp
- src/algorithms/spectral/gfcc.h
I added inputSize parameter with default value 1025 as it is set in ERBBands.
Updated a cout to E_INFO std output.
> GFCC inputsize parameter

- wscript
Explaining itself
https://code.google.com/p/android/issues/detail?id=175589
> Android 6 needs SONAME in library metadata

- doc/sphinxdoc/_templates/index.html
- doc/sphinxdoc/_templates/sphinxdoc_mtg/static/sphinxdoc_mtg.css_t
Sorry for the previous wrong pull request. Here is the right one.
> Fix behaviour of navmenu on resizing, improve readability

- src/algorithms/spectral/gfcc.cpp
- src/algorithms/spectral/gfcc.h
- test/src/unittest/spectral/test_gfcc.py
I've finished testing the behavior of the GFCC.
> GFCC in natural, power dB, amplitude dB or natural log

- src/algorithms/spectral/gfcc.cpp
- src/algorithms/spectral/gfcc.h
- 'type'
- 'dctType'
Also moved the dB type pointer association to Configure() to make it faster
> GFCC: Adding missing parameters: (#501)

- test/src/unittest/spectral/test_erbbands.py
Created test according to #270
The test is based on the MelBands test, but adding the `width` parameter of the ERBBands. I also used the current ERBBands values as the expected result in the regression test.
> ERBBands_test

- src/python/essentia/standard.py
- test/src/unittest/base/test_check_view_or_copy.py
Modification in the python parser in order to check if an input numpy array is a view or a copy. If it is a view, it copies the data to a new array. 
There is also a base test in order to check the proper behavior.
> Check if an array is a view or a copy

- src/algorithms/io/audioloader.cpp
- src/algorithms/io/audioloader.h
- src/algorithms/io/easyloader.cpp
- src/algorithms/io/easyloader.h
- src/algorithms/io/monoloader.cpp
- src/algorithms/io/monoloader.h
- test/src/unittest/io/test_audioloader_streaming.py
The update includes `AudioLoader`, `Monoloader` and  `EasyLoader`. The streaming test has also been updated.
> Update of load algorithms to support multistreams #552

- doc/sphinxdoc/_templates/index.html
Make documentation mobile-friendly.
> Docs reorganize

- src/essentia/streaming/algorithms/ringbufferinput.cpp
- src/essentia/streaming/algorithms/ringbufferinput.h
- src/essentia/streaming/algorithms/ringbufferoutput.cpp
- src/essentia/streaming/algorithms/ringbufferoutput.h
Almost closes MTG/essentia#641.
> Added `category` field to RingBufferInput/RingBufferOutput. 

- Essentia Licensing.txt
- src/3rdparty/cephes/bessel/bessel.h
- src/3rdparty/cephes/bessel/gamma.cpp
- src/3rdparty/cephes/bessel/hyperg.cpp
- src/3rdparty/cephes/bessel/iv.cpp
- src/3rdparty/cephes/bessel/polevl.cpp
- src/essentia/essentiamath.h
- Put Cephes methods under a namespace 
- Add Cephes licensing notes
> Cephes fixes

- FAQ.md
The following points are covered:
- How to retrain a model with a given set of parameters
- How to get insights about the parameters by looking at the `report.csv` file
> Add FAQ about Gaia updates

- src/algorithms/tonal/pitchyinfft.cpp
- src/algorithms/tonal/pitchyinfft.h
This feature is introduced following the behavior of [aubio](https://aubio.org/) after the discussion on #893.
> Add tolerance parameter to PitchYinFFT

- .travis.yml
- essentia.pc.in
- setup.py
- src/examples/wscript
- src/python/wscript
- src/wscript
- travis/build_wheels.sh
- wscript
- Rename dependencies_list -> default_libs
- Create a lib_map dictionary so we can get package names from their
LIB_KEY. This allows minimal code modifications if a package changes
its name in future
- Rename WITH_LIBS -> LIGHTWEIGHT for consistency
- Rename WITH_LIBS_LIST -> CHECK_LIBS for readability
- Improve the Gaia2 inclusion logic for readability
- Rename USES -> USE_LIBS
- Add Requires.private field to the Essentia .pc file
> Several improvements related to Waf

- src/algorithms/standard/vectorrealtotensor.cpp
- src/python/typedefs.h
- src/python/wscript
- test/src/unittests/machinelearning/test_tensorflowpredict_streaming.py
Some fixes to make builds on Mac OS working again. This should also resolve https://github.com/MTG/homebrew-essentia/issues/17.
> MacOS build fixes for TensorFlow related algorithms

- AUTHORS
- FAQ.md
- doc/sphinxdoc/installing.rst
This PR updates the outdated instructions for building Essentia with Emscripten.
> Updates instructions for building Essentia with Emscripten in the documentation

- packaging/build_3rdparty_static_debian.sh
- packaging/build_3rdparty_static_win32.sh
- packaging/debian_3rdparty/build_chromaprint.sh
- packaging/debian_3rdparty/build_eigen3.sh
- packaging/debian_3rdparty/build_ffmpeg.sh
- packaging/debian_3rdparty/build_fftw3.sh
- packaging/debian_3rdparty/build_gaia.sh
- packaging/debian_3rdparty/build_lame.sh
- packaging/debian_3rdparty/build_libsamplerate.sh
- packaging/debian_3rdparty/build_qt.sh
- packaging/debian_3rdparty/build_taglib.sh
- packaging/debian_3rdparty/build_tensorflow.sh
- packaging/debian_3rdparty/build_yaml.sh
- packaging/debian_3rdparty/build_zlib.sh
- packaging/win32_3rdparty/build_chromaprint.sh
- packaging/win32_3rdparty/build_eigen3.sh
- packaging/win32_3rdparty/build_ffmpeg.sh
- packaging/win32_3rdparty/build_fftw3.sh
- packaging/win32_3rdparty/build_lame.sh
- packaging/win32_3rdparty/build_libsamplerate.sh
- packaging/win32_3rdparty/build_taglib.sh
- packaging/win32_3rdparty/build_yaml.sh
- packaging/win32_3rdparty/build_zlib.sh
> Stop immediately if any command in a script fails

- test/src/unittests/rhythm/test_onsetdetection.py
- test/src/unittests/rhythm/test_rhythmextractor.py
-onset detection functions used in assertEqual asserts 
-assertEqualVector tests corrrections
-redundant commented out code removed
> Request to add additions to the onsetdetection function

- test/src/unittests/tonal/test_pitchyinprobabilities.py
- test/src/unittests/tonal/test_pitchyinprobabilitiesHMM.py
Opening PR for incremental updates on UT files:
tests for pitchyinprobabilities are covered in pitchyinprobabilistic
> Adding dummy tests for PitchYinProbabilities*

- src/examples/python/essentia-tensorflow_real-time_auto-tagging.ipynb
- src/examples/python/essentia-tensorflow_real-time_simultaneous_classifiers.ipynb
- A real-time auto-tagging example
- A real-time system with four classifiers operating simultaneously
> Add jupyter notebooks with real-time examples

- src/algorithms/rhythm/percivalevaluatepulsetrains.cpp
- src/algorithms/standard/binaryoperator.cpp
- src/algorithms/standard/binaryoperatorstream.cpp
- test/src/unittests/filters/test_maxfilter.py
- test/src/unittests/filters/test_medianfilter.py
- test/src/unittests/standard/test_binaryoperatorstream.py
- test/src/unittests/standard/test_unaryoperatorstream.py
Adding 2 of the 5 tests from the group  " Generic math and filters".
> Unit tests for BinaryOperatorStream, UnaryOperatorStream, MaxFilter, and MedianFilter

- src/algorithms/standard/constantq.h
Added the delete to correct leakage and reran the Regression test for 
https://github.com/MTG/essentia/issues/1143
> ConstantQ leaks object #1143

- doc/sphinxdoc/_templates/documentation.html
- doc/sphinxdoc/_templates/sphinxdoc_mtg/base.html
- doc/sphinxdoc/conf.py
- doc/sphinxdoc/models.rst
New page with a complete overview of all available models.
> New doc page for Essentia TensorFlow models

- doc/sphinxdoc/models.rst
Inference example for Spleeter missing from the previous PR #1222
> Add Spleeter inference example

- packaging/debian_3rdparty/build_zlib.sh
Fixed the incorrect zlib download location issue
> Update zlib download location

- src/essentia/debugging.cpp
> Improve logging on Android platform

- .github/workflows/build-docs.yml
Add `sphinx-copybutton` in `build-docs.yml`
> [fix] Add dependencies for copy button
